server:
  port: ${PORT:8080}
  shutdown: graceful

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=require&prepareThreshold=0
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000
      max-lifetime: 1200000
      connection-timeout: 100000
      pool-name: ${POOL_NAME}

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true


jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}

otp-service:
  key: ${OTP_KEY}
  base-url: ${OTP_BASE_URL}
  customer-id: ${OTP_CUSTOMER_ID}
  email-id: ${OTP_EMAIL_ID}
  token-path: "/auth/v1/authentication/token"
  send-otp-path: "/verification/v3/send"
  validate-path: "/verification/v3/validateOtp"

default:
  phone-number: ${PHONE}
  role: ${Role}
